# Generated by Django 4.2 on 2023-04-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='editeur',
            old_name='title',
            new_name='nom',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Editeur',
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=250)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.auteur')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.editeur')),
                ('genre', models.ManyToManyField(to='backoffice.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.livre')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.stock')),
                ('usure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.usure')),
            ],
        ),
        migrations.CreateModel(
            name='emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=250)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.adherent')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.exemplaire')),
            ],
        ),
    ]
